# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mueejalbasit/projects/Disaster-Oriented-Programming

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mueejalbasit/projects/Disaster-Oriented-Programming

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mueejalbasit/projects/Disaster-Oriented-Programming/CMakeFiles /Users/mueejalbasit/projects/Disaster-Oriented-Programming//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mueejalbasit/projects/Disaster-Oriented-Programming/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HMS

# Build rule for target.
HMS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HMS
.PHONY : HMS

# fast build rule for target.
HMS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/build
.PHONY : HMS/fast

src/complaint.o: src/complaint.cpp.o
.PHONY : src/complaint.o

# target to build an object file
src/complaint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/complaint.cpp.o
.PHONY : src/complaint.cpp.o

src/complaint.i: src/complaint.cpp.i
.PHONY : src/complaint.i

# target to preprocess a source file
src/complaint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/complaint.cpp.i
.PHONY : src/complaint.cpp.i

src/complaint.s: src/complaint.cpp.s
.PHONY : src/complaint.s

# target to generate assembly for a file
src/complaint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/complaint.cpp.s
.PHONY : src/complaint.cpp.s

src/database_handler.o: src/database_handler.cpp.o
.PHONY : src/database_handler.o

# target to build an object file
src/database_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/database_handler.cpp.o
.PHONY : src/database_handler.cpp.o

src/database_handler.i: src/database_handler.cpp.i
.PHONY : src/database_handler.i

# target to preprocess a source file
src/database_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/database_handler.cpp.i
.PHONY : src/database_handler.cpp.i

src/database_handler.s: src/database_handler.cpp.s
.PHONY : src/database_handler.s

# target to generate assembly for a file
src/database_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/database_handler.cpp.s
.PHONY : src/database_handler.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/notice_board.o: src/notice_board.cpp.o
.PHONY : src/notice_board.o

# target to build an object file
src/notice_board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/notice_board.cpp.o
.PHONY : src/notice_board.cpp.o

src/notice_board.i: src/notice_board.cpp.i
.PHONY : src/notice_board.i

# target to preprocess a source file
src/notice_board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/notice_board.cpp.i
.PHONY : src/notice_board.cpp.i

src/notice_board.s: src/notice_board.cpp.s
.PHONY : src/notice_board.s

# target to generate assembly for a file
src/notice_board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/notice_board.cpp.s
.PHONY : src/notice_board.cpp.s

src/user.o: src/user.cpp.o
.PHONY : src/user.o

# target to build an object file
src/user.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/user.cpp.o
.PHONY : src/user.cpp.o

src/user.i: src/user.cpp.i
.PHONY : src/user.i

# target to preprocess a source file
src/user.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/user.cpp.i
.PHONY : src/user.cpp.i

src/user.s: src/user.cpp.s
.PHONY : src/user.s

# target to generate assembly for a file
src/user.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HMS.dir/build.make CMakeFiles/HMS.dir/src/user.cpp.s
.PHONY : src/user.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HMS"
	@echo "... src/complaint.o"
	@echo "... src/complaint.i"
	@echo "... src/complaint.s"
	@echo "... src/database_handler.o"
	@echo "... src/database_handler.i"
	@echo "... src/database_handler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/notice_board.o"
	@echo "... src/notice_board.i"
	@echo "... src/notice_board.s"
	@echo "... src/user.o"
	@echo "... src/user.i"
	@echo "... src/user.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

